/* Categorias de livros */
INSERT INTO categorias (nome) VALUES
('Ficção'),
('Romance'),
('Fantasia'),
('Ficção Científica'),
('Mistério'),
('Suspense'),
('Terror'),
('Aventura'),
('Drama'),
('Poesia'),
('Biografia'),
('Autobiografia'),
('História'),
('Filosofia'),
('Psicologia'),
('Religião'),
('Espiritualidade'),
('Negócios'),
('Economia'),
('Finanças'),
('Tecnologia'),
('Programação'),
('Ciência'),
('Matemática'),
('Educação'),
('Autoajuda'),
('Saúde'),
('Culinária'),
('Arte'),
('Música'),
('Quadrinhos'),
('Mangá'),
('Infantil'),
('Juvenil'),
('Young Adult'),
('Policial'),
('Crônicas'),
('Ensaios'),
('Política'),
('Direito'),
('Medicina'),
('Viagens'),
('Esportes'),
('Idiomas');


/* Livros de teste */
INSERT INTO livros (
    titulo,
    autor,
    editora,
    ano_publicacao,
    id_categoria
) VALUES
('Dom Casmurro', 'Machado de Assis', 'Globo', 1899, 1),
('Orgulho e Preconceito', 'Jane Austen', 'Penguin', 1813, 2),
('Harry Potter e a Pedra Filosofal', 'J.K. Rowling', 'Rocco', 1997, 3),
('Duna', 'Frank Herbert', 'Aleph', 1965, 4),
('Assassinato no Expresso do Oriente', 'Agatha Christie', 'HarperCollins', 1934, 5),
('O Código Da Vinci', 'Dan Brown', 'Arqueiro', 2003, 6),
('It: A Coisa', 'Stephen King', 'Suma', 1986, 7),
('Percy Jackson e o Ladrão de Raios', 'Rick Riordan', 'Intrínseca', 2005, 8),
('Hamlet', 'William Shakespeare', 'Penguin', 1603, 9),
('Antologia Poética', 'Carlos Drummond de Andrade', 'Record', 1962, 10),
('Steve Jobs', 'Walter Isaacson', 'Companhia das Letras', 2011, 11),
('Minha História', 'Michelle Obama', 'Objetiva', 2018, 12),
('Sapiens', 'Yuval Noah Harari', 'L&PM', 2011, 13),
('A República', 'Platão', 'Martin Claret', 380, 14),
('Inteligência Emocional', 'Daniel Goleman', 'Objetiva', 1995, 15),
('O Poder do Hábito', 'Charles Duhigg', 'Objetiva', 2012, 26),
('Código Limpo', 'Robert C. Martin', 'Alta Books', 2008, 22),
('O Gene', 'Siddhartha Mukherjee', 'Companhia das Letras', 2016, 23),
('O Homem que Calculava', 'Malba Tahan', 'Record', 1938, 24),
('Turma da Mônica', 'Mauricio de Sousa', 'Panini', 1970, 31);